create table CONFERENCES (
    ID INT PRIMARY KEY NOT NULL,
    CITYV VARCHAR(80) NOT NULL,
    AIRPORT CHAR(3),
    SEATS INT  
);
create table SHUTTLES (
    ID INT PRIMARY KEY NOT NULL,
    AIRPORT CHAR(3),
    TIME TIME,
    SEATS INT  
);